sudo: required
language: java
jdk: openjdk8

services:
  - docker

script:
  - ./mvnw clean install

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export IMAGE_NAME=vatadepalli/localitecore
  - docker build -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME
  - docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: localite-core
