sudo: required
language: java
jdk: openjdk8

script:
  - ./mvnw clean install
  - zip core.zip ./target/core.jar

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "thelocalite-core"
  env: "localite"
  bucket_name: "thelocalite-core"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
